apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-health
spec:
  params:
    - name: app-hostname
      description: application protocol + hostname, e.g. https://example.com
    - name: health-endpoint
      description: application health endpoint, e.g. /health
      default: ""
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
    - name: task-image
      description: image used to execute this task
      default: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.2"
  steps:
    - name: check-health
      image: $(params.task-image)
      script: |
        #!/bin/bash
        set -e -o pipefail

        if [ $(params.pipeline-debug) == 1 ]; then
            pwd
            env
            trap env EXIT
            set -x
        fi

        MYURLS=($(echo "$(params.app-hostname)" | tr ',' '\n'))
        for i in "${!MYURLS[@]}"
        do
          if [ $(curl -isL -o /dev/null -w "%{http_code}" "${MYURLS[i]}$(params.health-endpoint)") == 200 ]; then
            echo "Successfully reached health endpoint at ${MYURLS[i]}$(params.health-endpoint)"
            echo "====================================================================="
          elif [ $(curl -isL -o /dev/null -w "%{http_code}" "${MYURLS[i]}") == 200 ]; then
            echo "Successfully reached application at ${MYURLS[i]}"
            echo "====================================================================="
          else
            echo "Could not reach health endpoint at ${MYURLS[i]} or at ${MYURLS[i]}$(params.health-endpoint)"
            exit 1
          fi
        done
